# Generated by Django 4.0.4 on 2022-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text='Required. 128 characters or fewer.', max_length=128, verbose_name='password'),
        ),
    ]
